# -*- coding: utf-8 -*-
"""Sampling_Distribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/chhayayadav/Sampling-Distribution/blob/master/Sampling_Distribution.ipynb
"""

from scipy.stats import norm
import matplotlib.pyplot as plt
Z0= input("enter value of Z0 and calculate P(Z<Z0)")
norm.cdf(float(Z0), loc=0, scale=1)

from scipy.stats import chi2
alpha= input("enter value of alpha ")
dof= input("enter degree of freedoms")
chi2.isf(float(alpha),int(dof), loc=0, scale=1)

from scipy.stats import t
alpha= input("enter value of alpha ")
dof= input("enter degree of freedoms")
t.cdf(float(alpha),int(dof), loc=0, scale=1)

from scipy.stats import f
alpha= input("enter value of alpha ")
dofn= input("enter degree of freedoms of numerator")
dofd= input("enter degree of freedoms of denominator")
f.cdf(float(alpha),int(dofn),int(dofd),loc=0, scale=1)